backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: '[skip ci] Upload "{{path}}"'
    deleteMedia: '[skip ci] Delete "{{path}}"'

local_backend: true

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/navbar.md"
        label: "Navigation Buttons"
        name: "navbar"
        fields:
          - {label: "Logo", name: "logo", widget: "string"}
          - {label: "Title", name: "title", widget: "string"}
          - label: "Navigation Menu"
            name: "menu"
            widget: "list"
            fields:
              - {label: "Text", name: "text", widget: "string"}
              - label: "Dropdown Links"
                name: "links"
                widget: "list"
                fields:
                  - {label: "Link Text", name: "text", widget: "string"}
                  - {label: "Link URL", name: "url", widget: "string"}
      - file: "content/hero-section.md"
        label: "Hero Section"
        name: "hero-section"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Button Text", name: "buttonText", widget: "string"}
          - {label: "Background Image", name: "backgroundImage", widget: "image"}
      - file: "content/stats-section.md"
        label: "Stats Section"
        name: "stats-section"
        fields:
          - {label: "Image", name: "image", widget: "string"}
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "Subheading", name: "subheading", widget: "string"}
          - {label: "Text", name: "text", widget: "string"}
          - {label: "CTA", name: "cta", widget: "string"}
          - {label: "CTA Link", name: "ctaLink", widget: "string"}
      - file: "content/content-grid.md"
        label: "Content Grid - Card Data"
        name: "content-grid"
        fields:
          - label: "Card Data"
            name: "cardData"
            widget: "list"
            fields:
              - {label: "Image", name: "image", widget: "string"}
              - {label: "Heading", name: "heading", widget: "string"}
              - {label: "Text", name: "text", widget: "string"}
              - {label: "CTA", name: "cta", widget: "string"}
              - {label: "CTA Link", name: "ctaLink", widget: "string"}
      - file: "content/about.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: "Logo Icon", name: "logo", widget: "string"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "content/get-involved.md"
        label: "Get Involved Page"
        name: "get-involved"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Intro", name: "intro", widget: "markdown"}
          - label: "Sections"
            name: "sections"
            widget: "list"
            fields:
              - {label: "Section Title", name: "sectionTitle", widget: "string"}
              - {label: "Section Body", name: "sectionBody", widget: "markdown"}

  - name: "victims"
    label: "Victims"
    folder: "content/victims"
    create: true
    slug: "{{name}}-{{date}}"
    fields:
      - {label: "Name", name: "name", widget: "string", required: true}
      - {label: "Age", name: "age", widget: "number", required: true}
      - {label: "Victim Type", name: "victimType", widget: "select", options: ["Pedestrian", "Bicyclist", "Motorcyclist", "Driver"], required: true}
      - {label: "Location", name: "location", widget: "string", required: true}
      - {label: "Date", name: "date", widget: "datetime", date_format: "MM/DD/YYYY", time_format: false, required: true}
      - {label: "Time", name: "time", widget: "datetime", date_format: false, time_format: "HH:mm", required: true}
      - {label: "Photo Credit", name: "photoCredit", widget: "string"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Description", name: "body", widget: "markdown", required: true}









