backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: '[skip ci] Upload "{{path}}"'
    deleteMedia: '[skip ci] Delete "{{path}}"'

local_backend: true


media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/hero-section.md"
        label: "Hero Section"
        name: "hero-section"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Button Text", name: "buttonText", widget: "string"}
          - {label: "Background Image", name: "backgroundImage", widget: "image"}
      - file: "content/about.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: "Logo Icon", name: "logo", widget: "string"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "content/get-involved.md"
        label: "Get Involved Page"
        name: "get-involved"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Intro", name: "intro", widget: "markdown"}
          - label: "Sections"
            name: "sections"
            widget: "list"
            fields:
              - {label: "Section Title", name: "sectionTitle", widget: "string"}
              - {label: "Section Body", name: "sectionBody", widget: "markdown"}

          - label: "Navigation Buttons"
            name: "menu"
            widget: "list"
            fields:
            - {label: "Text", name: "text", widget: "string"}
            - label: "Dropdown Items"
              name: "links"
              widget: "list"
              fields:
                - {label: "Link Text", name: "text", widget: "string"}
                - {label: "Link URL", name: "url", widget: "string"}
